### ISSUE TITLE
versions 8.1.0 Error: Cannot find module 'p-finally'

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/versions#18]
```log
> npm run patch

> Stylus-DeepDark@2.2.2 patch C:\Users\Joker\github\Stylus-DeepDark-Upstream
> versions -p -d -C patch StylusDeepDark.user.css

internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'p-finally'
Require stack:
- C:\Users\Joker\github\Stylus-DeepDark-Upstream\node_modules\execa\lib\kill.js
- C:\Users\Joker\github\Stylus-DeepDark-Upstream\node_modules\execa\index.js
- C:\Users\Joker\github\Stylus-DeepDark-Upstream\node_modules\versions\versions.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Joker\github\Stylus-DeepDark-Upstream\node_modules\execa\lib\kill.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Stylus-DeepDark@2.2.2 patch: `versions -p -d -C patch StylusDeepDark.user.css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Stylus-DeepDark@2.2.2 patch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Joker\AppData\Roaming\npm-cache\_logs\2020-03-05T15_22_00_438Z-debug.log
```

`npm i p-finally` to fix issue

## main log

```log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'patch'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.1.0
4 verbose run-script [ 'prepatch', 'patch', 'postpatch' ]
5 info lifecycle Stylus-DeepDark@2.2.2~prepatch: Stylus-DeepDark@2.2.2
6 info lifecycle Stylus-DeepDark@2.2.2~patch: Stylus-DeepDark@2.2.2
7 verbose lifecycle Stylus-DeepDark@2.2.2~patch: unsafe-perm in lifecycle true
8 verbose lifecycle Stylus-DeepDark@2.2.2~patch: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Joker\github\Stylus-DeepDark-Upstream\node_modules\.bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_162\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_172\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\Git\cmd;C:\Users\Joker\AppData\Local\Microsoft\WindowsApps;C:\Users\Joker\AppData\Local\atom\bin;C:\Users\Joker\AppData\Roaming\npm;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
9 verbose lifecycle Stylus-DeepDark@2.2.2~patch: CWD: C:\Users\Joker\github\Stylus-DeepDark-Upstream
10 silly lifecycle Stylus-DeepDark@2.2.2~patch: Args: [ '/d /s /c', 'versions -p -d -C patch StylusDeepDark.user.css' ]
11 silly lifecycle Stylus-DeepDark@2.2.2~patch: Returned: code: 1  signal: null
12 info lifecycle Stylus-DeepDark@2.2.2~patch: Failed to exec patch script
13 verbose stack Error: Stylus-DeepDark@2.2.2 patch: `versions -p -d -C patch StylusDeepDark.user.css`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1000:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
14 verbose pkgid Stylus-DeepDark@2.2.2
15 verbose cwd C:\Users\Joker\github\Stylus-DeepDark-Upstream
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "patch"
18 verbose node v12.1.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error Stylus-DeepDark@2.2.2 patch: `versions -p -d -C patch StylusDeepDark.user.css`
22 error Exit status 1
23 error Failed at the Stylus-DeepDark@2.2.2 patch script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by silverwind** [comment]
Strange. What version of execa is in `node_modules\execa\package.json`?

**Comment by the-j0k3r** [comment]
yea 3.4.0, not 4.0.0

My bad.. Clearly npm doesnt work well here. updating deps via updates is almost always a disaster.

**Comment by silverwind** [comment]
I never have any such issues, but I mostly use `yarn` (v1) these days. Also your node/npm are quite a bit out of date.

**Comment by the-j0k3r** [comment]
If I upgrade then version wont work anymore here
